version: "3.10"

services:
  # Service for RabbitMQ
  rabbitmq:
    image: rabbitmq:management
    command: rabbitmq-server
    tty: true
    ports:
      - "5672:5672"
      - "15672:15672"

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - upload-service
      - process-service

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      - ./db/init-scripts:/docker-entrypoint-initdb.d

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  upload-service:
    build: ./upload-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - shared_volume:/code/uploads/
    env_file:
      - ./upload-service/.env
    ports:
      - "8001:8000"
    depends_on:
      - auth-service
      - rabbitmq

  process-service:
    build: ./process-service
    volumes:
      - shared_volume:/code/uploads/
    env_file:
      - ./process-service/.env
    depends_on:
      - rabbitmq

  auth-service:
    build: ./auth-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./auth-service/:/app/
    env_file:
      - ./auth-service/.env
    ports:
      - "8002:8000"

volumes:
  shared_volume:
